apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: employee-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: employee-service
    spec:
      containers:
      - name: employee-service
        image: vamshi533/vamshik8s:employee-service
        ports:
        - containerPort: 80
